#: Add `include my.conf` to the LAST line of kitty.conf
#: After editing this file, press Ctrl+Shift+F5 in Kitty to reload

#: ===== Font =====
font_family CodeNewRoman Nerd Font
font_size 14.0

#: ===== Window behavior =====
remember_window_size no
remember_window_position no
hide_window_decorations no

initial_window_width 100c
initial_window_height 30c

#: Window padding (top, right, bottom, left)
window_padding_width 0 10 5 10

#: Enable scrollbar
# scrollbar scrolled

#: ===== Theme (choose ONE) =====

#: ---------- Black ----------
# background #000000
# foreground #ffffff

#: ---------- White ----------
background #ffffff
foreground #000000

#: ===== Transparency =====
# background_opacity 0.85

#: Titlebar follows background
macos_titlebar_color background

#: Text selection color
# selection_background #a0c4ff
# selection_foreground #ffffff