#: Add `include my.conf` to the LAST line of kitty.conf
#: After editing this file, press Ctrl+Shift+F5 in Kitty to reload

#: ===== Font =====
font_family CodeNewRoman Nerd Font Mono
font_size 14.0

#: ===== Window behavior =====
remember_window_size no
remember_window_position no
hide_window_decorations no

initial_window_width 100c
initial_window_height 30c

#: Window padding (top, right, bottom, left)
window_padding_width 0 10 5 10

#: Enable scrollbar
# scrollbar scrolled

#: ===== Theme (choose ONE) =====

#: ---------- Black ----------
# background #000000
# foreground #ffffff

#: ---------- White ----------
background #ffffff
foreground #000000

#: ===== Transparency ===== (0.0-1.0)
# background_opacity 0.8

#: Titlebar follows background
macos_titlebar_color background

#: Text selection color
# selection_background #a0c4ff
# selection_foreground #ffffff

#: ===== Background Image =====
#: Path to your background image (must be PNG/JPEG/WEBP/TIFF/GIF/BMP)
background_image ~/.config/kitty/kitty.png

#: Background image layout (Options: tiled, mirror-tiled, scaled, clamped, centered, cscaled)
background_image_layout scaled

#: Whether to use linear interpolation when scaling the background image
background_image_linear no

#: Tinting factor for the background image (0.0-1.0)
background_tint 0.3

#: Tinting factor for the window gaps (0.0-1.0)
background_tint_gaps 1.0